### ISSUE TITLE
Could not find gem 'chem_scanner' in any of the gem sources listed.

### ISSUE THREAD

**Issue by jayminSuhagiya** [ComPlat/chem_scanner#1]
While installing is shows that there is no gem like chem_scanner.

Used both ways to install and getting same error.

ERROR:  Could not find a valid gem 'chem_scanner' (>= 0) in any repository ( Using "gem install chem_scanner").

Error: - 
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'chem_scanner x64-mingw32' in any of the gem sources listed
in your Gemfile.

Any solutions to use this package.

**Comment by HamzaShaikh17** [comment]
I AM FACING THE SAME ISSUE:

ERROR:  Could not find a valid gem 'chem_scanner' (>= 0) in any repository
ERROR:  Possible alternatives: chemcaster, cms_scanner, arpscanner, chemspider, chessmonger

**Comment by CamAnNguyen** [comment]
@jayminSuhagiya  @HS1S Sorry I missed this report. I have pushed the new gem into rubygems, you can try again
